### Listar clientes
GET https://localhost:7048/api/clientes

### Obter um cliente específico pelo ID
GET https://localhost:7048/api/clientes/9

### Cadastrar um novo cliente
POST https://localhost:7048/api/clientes
Content-Type: application/json

{
    "nome" : "cliente 5",
    "idade" : 13,
    "email" : "cliente5@email.com"
}

### Atualizar um cliente existente pelo ID
PUT https://localhost:7048/api/clientes/10
Content-Type: application/json

{
    "nome" : "Felipe Correa",
    "idade" : 16,
    "email" : "felipe@gmail.com"
}

### Excluir um cliente pelo ID
DELETE https://localhost:7048/api/clientes/8

