### Listar filmes
GET https://localhost:7048/api/filmes

### Obter um filme específico pelo ID
GET https://localhost:7048/api/filmes/2

### Cadastrar um novo filme
POST https://localhost:7048/api/filmes
Content-Type: application/json

{
    "titulo" : "Titanic",
    "diretor" : "James Cameron",
    "anolancamento" : "1998"
}

### Atualizar um filme existente pelo ID
PUT https://localhost:7048/api/filmes/6
Content-Type: application/json

{
    "titulo" : "Avatar",
    "diretor" : "James Cameron",
    "anolancamento" : "2009"
}

### Excluir um filme pelo ID
DELETE https://localhost:7048/api/filmes/5
