### Listar filmes
GET https://localhost:7048/api/filmes

### Obter um filme específico pelo ID
GET https://localhost:7048/api/filmes/2

### Cadastrar um novo filme
POST https://localhost:7048/api/filmes
Content-Type: application/json

{
    "titulo" : "Titanic",
    "classificacaoetaria" : 14,
    "diretor" : "James Cameron",
    "anolancamento" : 1998
}

### Atualizar um filme existente pelo ID
PUT https://localhost:7048/api/filmes/11
Content-Type: application/json

{
    "titulo" : "a origem",
    "classificacaoetaria" : 12,
    "diretor" : "Christopher Nolan",
    "anolancamento" : 2006
}

### Excluir um filme pelo ID
DELETE https://localhost:7048/api/filmes/6
